[package]
name = "wrapsteel"
version = "0.0.1"
authors = ["Felix Dreissig <felix.dreissig@fau.de>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
path = "src/main.rs"

[features]
enclavization_lib = []

[dependencies]
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git", tag="v1.1.3" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", tag="v1.1.3", features = ["backtrace"] }
