[package]
name = "maxisign"
version = "0.0.1"
authors = ["Felix Dreissig <felix.dreissig@fau.de>"]
edition = "2018"
build = "../../support/build.rs"

[features]
enclavization_bin = []

[dependencies]
base64 = "0.13.0"
cadote_untrusted_runtime = { path = "../../support/cadote_untrusted_runtime" }
exitcode = "1.1.2"
ring = "0.16.20"
