[package]
name = "minimal_startup"
version = "0.0.1"
authors = ["Felix Dreissig <felix.dreissig@fau.de>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
path = "src/main.rs"

[features]
enclavization_lib = []

[dependencies]
cadote_trusted_runtime = { path = "../../support/cadote_trusted_runtime" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev="v1.1.3", features = ["backtrace", "untrusted_fs"] }
